services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

